apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-app  
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
        - name: backend
          image: your-backend-image
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "250m"   # Request 250 millicores (0.25 vCPU)
              memory: "256Mi" # Request 256 MB RAM
            limits:
              cpu: "500m"   # Limit to 500 millicores (0.5 vCPU)
              memory: "512Mi" # Limit to 512 MB RAM

        - name: frontend
          image: your-frontend-image
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "200m"   # Request 200 millicores (0.2 vCPU)
              memory: "128Mi" # Request 128 MB RAM
            limits:
              cpu: "400m"   # Limit to 400 millicores (0.4 vCPU)
              memory: "256Mi" # Limit to 256 MB RAM
